"""
programer:Roy Ali Hasan
Code:PYTHON 3.0
IDE:Visual Stdio Code
Comment:This is my First Python Program 
This program program  print binary conversion which enterd user
 """
print("You Can Convert Any Number Decimal To Binary Number  System(8bits&16bits Architacture)--->")
print("Enter a Decimal Num:")
num = input()
x = int(2)
rem1 = int(num) % int(x)
div1 = int(num)/int(x)
rem2 = int(div1) % int(x)
div2 = int(div1)/int(x)
rem3 = int(div2) % int(x)
div3 = int(div2)/int(x)
rem4 = int(div3) % int(x)
div4 = int(div3)/int(x)
rem5 = int(div4) % int(x)
div5 = int(div4)/int(x)
rem6 = int(div5) % int(x)
div6 = int(div5)/int(x)
rem7 = int(div6) % int(x)
div7 = int(div6)/int(x)
rem8 = int(div7) % int(x)
div8 = int(div7)/int(x)
rem9 = int(div8) % int(x)
div9 = int(div8)/int(x)
rem10 = int(div9) % int(x)
div10 = int(div9)/int(x)
rem11 = int(div10) % int(x)
div11 = int(div10)/int(x)
rem12 = int(div11) % int(x)
div12 = int(div11)/int(x)
rem13 = int(div12) % int(x)
div13 = int(div12)/int(x)
rem14 = int(div13) % int(x)
div14 = int(div13)/int(x)
rem15 = int(div14) % int(x)
div15 = int(div14)/int(x)
rem16 = int(div15) % int(x)
print("Binary Conversion Of <8bit> Architacture is : ", end="|")
print(rem8, rem7, rem6, rem5, rem4, rem3, rem2, rem1, end="|")
print("\n______________________________________&___________________________________")
print("Binary Conversion Of <16Bit> Architecture is:", end="|")
print(rem16, rem15, rem14, rem13, rem12, rem11, rem10, rem9,
      rem8, rem7, rem6, rem5, rem4, rem3, rem2, rem1, end="|")
print("\nPlz Enter For Exit", "thanku")
exit = input()
exit = print("\nBy by!!!!!>>>>>")
